name: clipboard_watcher
description: This plugin allows Flutter apps to watch clipboard changes.
version: 0.2.1
homepage: https://github.com/leanflutter/clipboard_watcher

platforms:
  linux:
  macos:
  windows:
  ios:
  android:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dependency_validator: ^3.2.3
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: ClipboardWatcherPlugin
      macos:
        pluginClass: ClipboardWatcherPlugin
      windows:
        pluginClass: ClipboardWatcherPlugin
      ios:
        pluginClass: ClipboardWatcherPlugin
      android:
        pluginClass: ClipboardWatcherPlugin
        package: clipboard.watcher
